"use client";

import { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "id" | "en";

type Primitive = string | number;
interface Dict {
  [key: string]: Primitive | Dict;
}

const id: Dict = {
  common: {
    back: "Kembali",
    save: "Simpan",
    saved: "Tersimpan!",
    cancel: "Batal",
    loading: "Memuat...",
    close: "Tutup",
    done: "Selesai",
  },
  dashboard: {
    title: "Dashboard",
    groupHome: "Beranda",
    groupLearning: "Belajar",
    groupInsights: "Wawasan",
    topic: "Topik Belajar",
    roadmap: "Roadmap",
    mentor: "Mentor AI",
    assessment: "Assessment",
    progress: "Progress",
    settings: "Pengaturan",
    logout: "Logout",
    selamatDatang: "Halo",
    search: "Cari topik atau materi...",
    notifications: "Notifikasi",
    markAllRead: "Tandai dibaca semua",
    profile: "Profil Saya",
    accountSettings: "Pengaturan Akun",
    darkMode: "Mode Gelap",
    lightMode: "Mode Terang",
    grade: {
      sd: "SD",
      smp: "SMP",
      sma: "SMA",
      mahasiswa: "Mahasiswa",
      self_learner: "Self Learner",
    },
    popularTopics: "Topik Populer",
    searchResults: "Hasil Pencarian",
    noResults: "Tidak ada hasil untuk",
  },
  home: {
    hello: "Selamat datang kembali, {name}",
    subtitle: "Lanjutkan dari tempat kamu terakhir belajar.",
    newTopicBtn: "Buat Topik Baru",
    studyHours: "Jam Belajar",
    activeTopics: "Topik Aktif",
    streakDays: "Streak Hari",
    avgProgress: "Rata-rata Progres",
    aiQuota: "Kuota AI hari ini",
    chat: "Chat",
    roadmap: "Roadmap",
    quiz: "Kuis",
    continueLearning: "Lanjutkan Belajar",
    roadmapReady: "Roadmap siap dilanjutkan.",
    noRoadmap: "Belum ada roadmap. Buat peta belajarnya sekarang!",
    continueBtn: "Lanjutkan",
    createRoadmapBtn: "Buat Roadmap",
    otherTopics: "Topik Aktif Lainnya",
    roadmapAvailable: "Roadmap tersedia",
    noRoadmapShort: "Belum ada roadmap",
    progress: "Progres",
    aiRecommendations: "Rekomendasi Belajar",
    createLearningMap: "Buat Peta Belajar",
    emptyTitle: "Belum ada topik aktif",
    emptyDesc: "Mari mulai perjalanan belajarmu. Tentukan topik pertama yang ingin kamu pelajari bersama AI Mentor.",
    startLearning: "Mulai Belajar",
    newTopicTitle: "Topik Belajar Baru",
    whatLearn: "Apa yang ingin kamu pelajari?",
    topicPlaceholder: "Contoh: Python Dasar, Machine Learning, Aljabar...",
    createRoadmapAi: "Buat Peta Belajar AI (Roadmap)",
    learner: "Pembelajar",
    loadFail: "Gagal memuat data.",
    createFail: "Gagal membuat topik.",
  },
  roadmap: {
    easy: "Mudah",
    medium: "Sedang",
    hard: "Sulit",
    loadTopicsFail: "Gagal memuat daftar topik.",
    loadRoadmapFail: "Gagal memuat roadmap.",
    createFail: "Gagal membuat roadmap.",
    updateFail: "Gagal memperbarui langkah.",
    pickTopic: "Pilih Topik Belajar",
    pickTopicDesc: "Pilih salah satu topikmu untuk melihat peta belajar (roadmap) yang sudah disusun AI.",
    noTopics: "Belum ada topik. Buat topik terlebih dahulu dari halaman Dashboard.",
    chooseTopic: "Pilih topik...",
    roadmapAvailableOpt: "(Roadmap tersedia)",
    roadmapReadyBadge: "Roadmap tersedia",
    noRoadmapBadge: "Belum ada roadmap",
    noRoadmapTitle: "Belum ada roadmap untuk topik ini",
    noRoadmapDesc: "Biarkan AI Mentor menyusun peta belajar langkah demi langkah untuk {topic}.",
    createRoadmap: "Buat Roadmap",
    generateAgain: "Generate Ulang Roadmap",
    quotaRoadmapExhausted: "Kuota harian untuk membuat roadmap telah habis.",
    demoMode: "Mode Demo",
    estimated: "Estimasi {hours} jam",
    steps: "{count} langkah",
    topicLabel: "Topik: {topic}",
    roadmapProgress: "Progres Peta Belajar",
    learningSteps: "Langkah Belajar",
    step: "Langkah {n}",
    markDone: "Tandai selesai",
    markNotDone: "Tandai belum selesai",
    openMaterial: "Buka Materi",
    askMentor: "Tanya Mentor",
    askMentorTooltip: "Tanya Mentor (Fast Track)",
    askPrompt: 'Kak, tolong jelaskan tentang langkah belajar "{step}" dalam topik "{topic}". Apa konsep utamanya dan bagaimana cara memahaminya?',
    openDesc: "Buka deskripsi",
    closeDesc: "Tutup deskripsi",
    noDesc: "Tidak ada deskripsi untuk langkah ini.",
    generatingTitle: "Menyusun Roadmap AI...",
    generatingDesc: "AI Mentor sedang menyusun langkah belajar terbaik untukmu.",
  },
  topik: {
    title: "Apa yang ingin kamu pelajari hari ini?",
    subtitle:
      "Tentukan topik pelajaran atau bidang keahlianmu. AI Mentor Buddio akan menganalisis dan menyusun peta jalan belajar yang disesuaikan khusus untukmu.",
    createFail: "Gagal membuat topik.",
    searchPlaceholder: "Contoh: React, Kalkulus, Fisika, TOEFL...",
    popularTopics: "Topik Populer",
    learners: "{learners} pembelajar",
    creatingTopic: "Menyiapkan topik...",
    createRoadmapBtn: "Buat Roadmap Belajar",
  },
  assessment: {
    listTitle: "Latihan Kuis",
    listDesc: "Uji pemahamanmu dengan soal yang disusun AI Mentor.",
    quotaDailyExhausted: "Kuota Harian Habis",
    generatingQuiz: "Sedang menyusun soal...",
    newQuizBtn: "Buat Kuis Baru",
    loadQuizzesFail: "Gagal memuat daftar kuis.",
    loadTopicsFail: "Gagal memuat topik.",
    newQuizFail: "Gagal membuat kuis baru.",
    submitFail: "Gagal mengumpulkan jawaban.",
    noTopicsTitle: "Belum ada topik",
    noTopicsDesc: "Buat topik belajar terlebih dahulu sebelum mengerjakan kuis.",
    pickTopic: "Pilih Topik",
    quizList: "Daftar Kuis ({count})",
    noQuizTitle: "Belum ada kuis untuk topik ini",
    noQuizDesc: 'Klik "Buat Kuis Baru" agar AI Mentor menyusun soal latihan untukmu.',
    questions: "{count} soal",
    demoMode: "Mode Demo",
    backToList: "Kembali ke Daftar",
    takingDesc: "Pilih satu jawaban untuk setiap soal, lalu kumpulkan jawabanmu.",
    answered: "{answered}/{total} terjawab",
    allAnswered: "Semua soal sudah terjawab. Siap dikumpulkan!",
    unansweredLeft: "Masih ada {count} soal yang belum dijawab.",
    submitAnswers: "Kumpulkan Jawaban",
    score: "Skor: {score}/{total} ({percent}%)",
    correct: "Benar",
    wrong: "Salah",
    retake: "Kerjakan Lagi",
    reviewAnswers: "Pembahasan Jawaban",
    yourAnswer: "Jawabanmu:",
    correctAnswer: "Jawaban benar:",
    unknownAnswer: "Tidak diketahui",
    explanation: "Penjelasan:",
    generatingModalTitle: "Sedang menyusun soal...",
    generatingModalDesc: "AI Mentor sedang meracik kuis terbaik untukmu. Mohon tunggu sebentar.",
  },
  mentor: {
    greeting: "Halo! Aku Kak Buddio, mentor belajarmu. Mau tanya apa hari ini?",
    loadTopicsFail: "Gagal memuat topik.",
    loadHistoryFail: "Gagal memuat riwayat chat.",
    sendFail: "Gagal mengirim pesan.",
    quotaExhausted: "Sisa kuota chat hari ini sudah habis.",
    deleteFail: "Gagal menghapus riwayat.",
    noTopicsTitle: "Belum ada topik belajar",
    noTopicsDesc: "Kamu perlu membuat topik belajar dulu sebelum bisa bertanya pada AI Mentor Buddio.",
    createTopicBtn: "Buat Topik Belajar",
    title: "Mentor AI Buddio",
    subtitle: "Tanya apa saja, Kak Buddio siap membantu belajarmu.",
    pickTopic: "Pilih Topik",
    chatQuotaLeft: "Sisa kuota chat hari ini:",
    demoMode: "Mode Demo",
    deleteHistory: "Hapus Riwayat",
    chatPlaceholder: "Tulis pertanyaanmu di sini...",
  },
  progress: {
    loadFail: "Gagal memuat data progres.",
    title: "Progres Belajar",
    subtitle: "Pantau perkembangan belajarmu bersama AI Mentor.",
    studyHours: "Jam Belajar",
    activeTopics: "Topik Aktif",
    streakDays: "Streak Hari",
    avgProgress: "Rata-rata Progres",
    aiQuota: "Kuota AI",
    chat: "Chat",
    roadmap: "Roadmap",
    quiz: "Kuis",
    left: "{value} sisa",
    perTopic: "Progres per Topik",
    studied: "{duration} belajar",
    emptyTitle: "Belum ada data progres",
    emptyDesc: "Mulai belajar topik pertamamu untuk melihat statistik dan perkembangan belajarmu di sini.",
    hourShort: "j",
    minuteShort: "m",
  },
  profile: {
    learner: "Pembelajar",
    title: "Profil Saya",
    subtitle: "Kelola informasi profil dan tujuan belajarmu.",
    editProfile: "Edit Profil",
    fullName: "Nama Lengkap",
    learningGoal: "Tujuan Belajar",
    fullNamePlaceholder: "Nama lengkap kamu",
    learningGoalPlaceholder: "Contoh: Lulus SNBT, menguasai Python, dll.",
    saveChanges: "Simpan Perubahan",
    saveSuccess: "Profil berhasil diperbarui.",
    saveFail: "Gagal memperbarui profil.",
  },
  materi: {
    notReady: "Materi belum tersedia",
    notReadyDesc: "Klik tombol di bawah agar AI Buddio menyusun materi pembelajaran lengkap.",
    generate: "Generate Materi Sekarang",
    introWelcome: "Selamat datang di materi ini!",
    introTitle: "Apa yang akan kita pelajari?",
    introDesc: "Sebelum mulai, ini gambaran singkat tentang apa yang akan kamu pelajari pada langkah ini.",
    introObjectiveLabel: "Ringkasan tujuan belajar",
    introObjective: "Kamu akan memahami \"{step}\" secara mendalam dan bertahap — mulai dari konsep dasar, contoh nyata, sampai latihan soal, dengan bimbingan personal sepanjang proses belajar.",
    introStepsLabel: "Cara belajar di Buddio",
    introSteps: "AI Buddio akan menyusun materi lengkap, lalu kamu bisa membaca, menandai bagian penting, bertanya langsung, dan mengerjakan latihan pemahaman.",
    introStart: "Mulai Belajar",
    introGeneratingLabel: "Menyusun materimu...",
    introStep: "Langkah {n}",
    generating: "Menyusun materi...",
    generatingDesc: "AI Buddio sedang menyiapkan materi lengkap untukmu.",
    coreTitle: "Materi Inti",
    highlightActive: "Mode Aktif — Blok teks",
    highlightInactive: "Aktifkan Highlight",
    highlightOn: "Highlight On",
    highlight: "Highlight",
    videoTitle: "Belajar Lewat Video",
    videoDesc: "Video relevan untuk memperdalam pemahamanmu.",
    noVideo: "Belum ada rekomendasi video yang valid untuk materi ini.",
    stillConfused: "Masih Bingung?",
    stillConfusedDesc: "Tanya Kak Buddio langsung tentang materi \"{step}\" ini.",
    askBuddio: "Tanya Kak Buddio",
    regenerate: "Regenerate Materi",
    exitStudyMode: "Keluar Mode Belajar",
    studyMode: "Mode Belajar",
    done: "Selesai",
    notes: "Catatan",
    notesTitle: "Catatan Belajar",
    notesPlaceholder: "Tulis catatan belajarmu di sini...\n\nContoh:\n- Poin penting yang harus diingat\n- Pertanyaan untuk ditanyakan ke Kak Buddio\n- Ringkasan versi sendiri",
    notesAuto: "Catatan tersimpan otomatis di browser ini ({count} karakter)",
    backToRoadmap: "Kembali ke Roadmap",
    topic: "Topik: {topic}",
    highlightLabel: "Highlight:",
    checkTitle: "Seberapa paham kamu?",
    checkDesc: "Beritahu Buddio agar bisa membantumu lebih baik.",
    iUnderstand: "Saya Paham",
    imConfused: "Masih Bingung",
    greatJob: "Hebat! Lanjutkan semangatmu!",
    markAgain: "Tandai ulang",
    confusedPrompt: "Tidak masalah! Pilih cara yang paling membantumu, dan Buddio akan menjelaskan dengan pendekatan itu.",
    followJelaskan: "Jelaskan dengan bahasa sederhana",
    followContoh: "Beri contoh konkret",
    followLangkah: "Jelaskan langkah demi langkah",
    followAnalogi: "Pakai analogi sehari-hari",
    followDalam: "Perdalam materinya",
    promptJelaskan: "Tolong jelaskan materi ini dengan bahasa yang lebih sederhana.",
    promptContoh: "Tolong berikan contoh konkret untuk materi ini.",
    promptLangkah: "Tolong jelaskan materi ini langkah demi langkah.",
    promptAnalogi: "Tolong jelaskan materi ini dengan analogi dari kehidupan sehari-hari.",
    promptDalam: "Tolong perdalam penjelasan materi ini.",
    promptJelaskanMateri: "Tolong bantu saya memahami materi \"{step}\" ini. ",
  },
  settings: {
    title: "Pengaturan",
    desc: "Kelola preferensi aplikasi, informasi profil, dan keamanan akunmu.",
    sectionTitle: "Pengaturan",
    sectionDesc: "Atur preferensi tampilan dan kebiasaan belajarmu.",
    theme: "Tema",
    language: "Bahasa",
    notifications: "Notifikasi",
    notificationsLabel: "Aktifkan notifikasi belajar",
    dailyGoal: "Target Belajar Harian (menit)",
    saveSettings: "Simpan Pengaturan",
    saved: "Pengaturan tersimpan.",
    loadError: "Gagal memuat pengaturan.",
    saveError: "Gagal menyimpan pengaturan.",
    profileTitle: "Profil",
    profileDesc: "Perbarui informasi dirimu agar pengalaman belajar lebih personal.",
    changePassword: "Ganti Password",
    changePasswordDesc: "Amankan akunmu dengan password baru.",
    fullName: "Nama Lengkap",
    fullNamePlaceholder: "Nama lengkap kamu",
    learningGoal: "Tujuan Belajar",
    learningGoalPlaceholder: "Contoh: Lulus UTBK, menguasai pemrograman...",
    oldPassword: "Password Lama",
    oldPasswordPlaceholder: "Password lama kamu",
    newPassword: "Password Baru",
    newPasswordPlaceholder: "Minimal 8 karakter",
    confirmPassword: "Konfirmasi Password Baru",
    confirmPasswordPlaceholder: "Ulangi password baru",
    saveProfile: "Simpan Profil",
    changePasswordBtn: "Ganti Password",
    passwordChanged: "Password berhasil diganti.",
    profileSaved: "Profil berhasil disimpan.",
    passwordMismatch: "Konfirmasi password tidak cocok.",
    passwordTooShort: "Password baru minimal 8 karakter.",
    passwordFail: "Gagal mengganti password.",
  },
};

const en: Dict = {
  common: {
    back: "Back",
    save: "Save",
    saved: "Saved!",
    cancel: "Cancel",
    loading: "Loading...",
    close: "Close",
    done: "Done",
  },
  dashboard: {
    title: "Dashboard",
    groupHome: "Home",
    groupLearning: "Learning",
    groupInsights: "Insights",
    topic: "Learning Topics",
    roadmap: "Roadmap",
    mentor: "AI Mentor",
    assessment: "Assessment",
    progress: "Progress",
    settings: "Settings",
    logout: "Logout",
    selamatDatang: "Hello",
    search: "Search topics or materials...",
    notifications: "Notifications",
    markAllRead: "Mark all read",
    profile: "My Profile",
    accountSettings: "Account Settings",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    grade: {
      sd: "Elementary",
      smp: "Middle School",
      sma: "High School",
      mahasiswa: "College",
      self_learner: "Self Learner",
    },
    popularTopics: "Popular Topics",
    searchResults: "Search Results",
    noResults: "No results for",
  },
  home: {
    hello: "Welcome back, {name}",
    subtitle: "Continue where you left off.",
    newTopicBtn: "Create New Topic",
    studyHours: "Study Hours",
    activeTopics: "Active Topics",
    streakDays: "Day Streak",
    avgProgress: "Avg Progress",
    aiQuota: "AI quota today",
    chat: "Chat",
    roadmap: "Roadmap",
    quiz: "Quiz",
    continueLearning: "Continue Learning",
    roadmapReady: "Roadmap ready to continue.",
    noRoadmap: "No roadmap yet. Create your learning map now!",
    continueBtn: "Continue",
    createRoadmapBtn: "Create Roadmap",
    otherTopics: "Other Active Topics",
    roadmapAvailable: "Roadmap available",
    noRoadmapShort: "No roadmap yet",
    progress: "Progress",
    aiRecommendations: "Learning Recommendations",
    createLearningMap: "Create Learning Map",
    emptyTitle: "No active topics yet",
    emptyDesc: "Start your learning journey. Pick your first topic to learn with your AI mentor.",
    startLearning: "Start Learning",
    newTopicTitle: "New Learning Topic",
    whatLearn: "What would you like to learn?",
    topicPlaceholder: "Example: Python Basics, Machine Learning, Algebra...",
    createRoadmapAi: "Create AI Learning Map (Roadmap)",
    learner: "Learner",
    loadFail: "Failed to load data.",
    createFail: "Failed to create topic.",
  },
  roadmap: {
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    loadTopicsFail: "Failed to load topic list.",
    loadRoadmapFail: "Failed to load roadmap.",
    createFail: "Failed to create roadmap.",
    updateFail: "Failed to update step.",
    pickTopic: "Choose Learning Topic",
    pickTopicDesc: "Pick one of your topics to see the learning map (roadmap) AI has prepared.",
    noTopics: "No topics yet. Create one first from the Dashboard page.",
    chooseTopic: "Choose a topic...",
    roadmapAvailableOpt: "(Roadmap available)",
    roadmapReadyBadge: "Roadmap available",
    noRoadmapBadge: "No roadmap yet",
    noRoadmapTitle: "No roadmap yet for this topic",
    noRoadmapDesc: "Let the AI mentor build a step-by-step learning map for {topic}.",
    createRoadmap: "Create Roadmap",
    generateAgain: "Regenerate Roadmap",
    quotaRoadmapExhausted: "Your daily roadmap quota has been used up.",
    demoMode: "Demo Mode",
    estimated: "Est. {hours} hours",
    steps: "{count} steps",
    topicLabel: "Topic: {topic}",
    roadmapProgress: "Learning Map Progress",
    learningSteps: "Learning Steps",
    step: "Step {n}",
    markDone: "Mark done",
    markNotDone: "Mark not done",
    openMaterial: "Open Material",
    askMentor: "Ask Mentor",
    askMentorTooltip: "Ask Mentor (Fast Track)",
    askPrompt: 'Please explain the learning step "{step}" in the topic "{topic}". What are the key concepts and how can I understand them?',
    openDesc: "Open description",
    closeDesc: "Close description",
    noDesc: "No description for this step.",
    generatingTitle: "Building AI Roadmap...",
    generatingDesc: "The AI mentor is preparing the best learning steps for you.",
  },
  topik: {
    title: "What would you like to learn today?",
    subtitle:
      "Choose a subject or skill you want to master. Buddio's AI mentor will analyze it and build a learning roadmap tailored just for you.",
    createFail: "Failed to create topic.",
    searchPlaceholder: "Example: React, Calculus, Physics, TOEFL...",
    popularTopics: "Popular Topics",
    learners: "{learners} learners",
    creatingTopic: "Preparing topic...",
    createRoadmapBtn: "Create Learning Roadmap",
  },
  assessment: {
    listTitle: "Quiz Practice",
    listDesc: "Test your understanding with questions created by the AI mentor.",
    quotaDailyExhausted: "Daily Quota Exhausted",
    generatingQuiz: "Preparing questions...",
    newQuizBtn: "Create New Quiz",
    loadQuizzesFail: "Failed to load quiz list.",
    loadTopicsFail: "Failed to load topics.",
    newQuizFail: "Failed to create a new quiz.",
    submitFail: "Failed to submit answers.",
    noTopicsTitle: "No topics yet",
    noTopicsDesc: "Create a learning topic before taking a quiz.",
    pickTopic: "Pick a Topic",
    quizList: "Quiz List ({count})",
    noQuizTitle: "No quizzes for this topic yet",
    noQuizDesc: 'Click "Create New Quiz" so the AI mentor can prepare practice questions for you.',
    questions: "{count} questions",
    demoMode: "Demo Mode",
    backToList: "Back to List",
    takingDesc: "Pick one answer for each question, then submit your answers.",
    answered: "{answered}/{total} answered",
    allAnswered: "All questions answered. Ready to submit!",
    unansweredLeft: "There are still {count} unanswered questions.",
    submitAnswers: "Submit Answers",
    score: "Score: {score}/{total} ({percent}%)",
    correct: "Correct",
    wrong: "Wrong",
    retake: "Retake",
    reviewAnswers: "Answer Review",
    yourAnswer: "Your answer:",
    correctAnswer: "Correct answer:",
    unknownAnswer: "Unknown",
    explanation: "Explanation:",
    generatingModalTitle: "Preparing questions...",
    generatingModalDesc: "The AI mentor is crafting the best quiz for you. Please wait a moment.",
  },
  mentor: {
    greeting: "Hello! I'm Buddio, your study mentor. What would you like to ask today?",
    loadTopicsFail: "Failed to load topics.",
    loadHistoryFail: "Failed to load chat history.",
    sendFail: "Failed to send message.",
    quotaExhausted: "Your daily chat quota is used up.",
    deleteFail: "Failed to delete history.",
    noTopicsTitle: "No learning topics yet",
    noTopicsDesc: "You need to create a learning topic before you can ask Buddio's AI mentor.",
    createTopicBtn: "Create Learning Topic",
    title: "Buddio AI Mentor",
    subtitle: "Ask anything, Buddio is here to help you learn.",
    pickTopic: "Pick a Topic",
    chatQuotaLeft: "Chat quota left today:",
    demoMode: "Demo Mode",
    deleteHistory: "Delete History",
    chatPlaceholder: "Type your question here...",
  },
  progress: {
    loadFail: "Failed to load progress data.",
    title: "Learning Progress",
    subtitle: "Track your learning progress with your AI mentor.",
    studyHours: "Study Hours",
    activeTopics: "Active Topics",
    streakDays: "Day Streak",
    avgProgress: "Avg Progress",
    aiQuota: "AI quota",
    chat: "Chat",
    roadmap: "Roadmap",
    quiz: "Quiz",
    left: "{value} left",
    perTopic: "Progress per Topic",
    studied: "{duration} studied",
    emptyTitle: "No progress data yet",
    emptyDesc: "Start learning your first topic to see your statistics and progress here.",
    hourShort: "h",
    minuteShort: "m",
  },
  profile: {
    learner: "Learner",
    title: "My Profile",
    subtitle: "Manage your profile information and learning goals.",
    editProfile: "Edit Profile",
    fullName: "Full Name",
    learningGoal: "Learning Goal",
    fullNamePlaceholder: "Your full name",
    learningGoalPlaceholder: "Example: Pass SNBT, master Python, etc.",
    saveChanges: "Save Changes",
    saveSuccess: "Profile updated successfully.",
    saveFail: "Failed to update profile.",
  },
  materi: {
    notReady: "Material not ready",
    notReadyDesc: "Click the button below so AI Buddio can prepare a complete learning material.",
    generate: "Generate Material Now",
    introWelcome: "Welcome to this material!",
    introTitle: "What are we going to learn?",
    introDesc: "Before you start, here is a quick overview of what you'll learn in this step.",
    introObjectiveLabel: "Learning goal summary",
    introObjective: "You'll understand \"{step}\" deeply and step by step — from the basic concepts, real examples, to practice questions, with personal guidance throughout your learning.",
    introStepsLabel: "How learning works on Buddio",
    introSteps: "AI Buddio will prepare the full material, then you can read, highlight key parts, ask questions, and do understanding checks.",
    introStart: "Start Learning",
    introGeneratingLabel: "Preparing your material...",
    introStep: "Step {n}",
    generating: "Preparing material...",
    generatingDesc: "AI Buddio is preparing your complete material.",
    coreTitle: "Core Material",
    highlightActive: "Active Mode — Select text",
    highlightInactive: "Enable Highlight",
    highlightOn: "Highlight On",
    highlight: "Highlight",
    videoTitle: "Learn with Videos",
    videoDesc: "Relevant videos to deepen your understanding.",
    noVideo: "No valid recommended videos for this material yet.",
    stillConfused: "Still Confused?",
    stillConfusedDesc: "Ask Buddio directly about this \"{step}\" material.",
    askBuddio: "Ask Buddio",
    regenerate: "Regenerate Material",
    exitStudyMode: "Exit Study Mode",
    studyMode: "Study Mode",
    done: "Done",
    notes: "Notes",
    notesTitle: "Study Notes",
    notesPlaceholder: "Write your study notes here...\n\nExample:\n- Key points to remember\n- Questions to ask Buddio\n- Your own summary",
    notesAuto: "Notes auto-saved in this browser ({count} characters)",
    backToRoadmap: "Back to Roadmap",
    topic: "Topic: {topic}",
    highlightLabel: "Highlights:",
    checkTitle: "How well do you understand?",
    checkDesc: "Tell Buddio so it can help you better.",
    iUnderstand: "I Understand",
    imConfused: "Still Confused",
    greatJob: "Great job! Keep the momentum!",
    markAgain: "Mark again",
    confusedPrompt: "No problem! Pick the approach that helps most, and Buddio will explain it that way.",
    followJelaskan: "Explain in simple words",
    followContoh: "Give a concrete example",
    followLangkah: "Explain step by step",
    followAnalogi: "Use a real-life analogy",
    followDalam: "Go deeper",
    promptJelaskan: "Please explain this material in simpler words.",
    promptContoh: "Please give a concrete example for this material.",
    promptLangkah: "Please explain this material step by step.",
    promptAnalogi: "Please explain this material with a real-life analogy.",
    promptDalam: "Please go deeper into this material.",
    promptJelaskanMateri: "Please help me understand this \"{step}\" material. ",
  },
  settings: {
    title: "Settings",
    desc: "Manage app preferences, profile information, and account security.",
    sectionTitle: "Settings",
    sectionDesc: "Customize display preferences and study habits.",
    theme: "Theme",
    language: "Language",
    notifications: "Notifications",
    notificationsLabel: "Enable study notifications",
    dailyGoal: "Daily Study Goal (minutes)",
    saveSettings: "Save Settings",
    saved: "Settings saved.",
    loadError: "Failed to load settings.",
    saveError: "Failed to save settings.",
    profileTitle: "Profile",
    profileDesc: "Update your information for a more personal learning experience.",
    changePassword: "Change Password",
    changePasswordDesc: "Secure your account with a new password.",
    fullName: "Full Name",
    fullNamePlaceholder: "Your full name",
    learningGoal: "Learning Goal",
    learningGoalPlaceholder: "Example: Pass UTBK, master programming...",
    oldPassword: "Old Password",
    oldPasswordPlaceholder: "Your old password",
    newPassword: "New Password",
    newPasswordPlaceholder: "Minimum 8 characters",
    confirmPassword: "Confirm New Password",
    confirmPasswordPlaceholder: "Repeat new password",
    saveProfile: "Save Profile",
    changePasswordBtn: "Change Password",
    passwordChanged: "Password changed successfully.",
    profileSaved: "Profile saved successfully.",
    passwordMismatch: "Passwords do not match.",
    passwordTooShort: "New password must be at least 8 characters.",
    passwordFail: "Failed to change password.",
  },
};

const dictionaries: Record<Language, Dict> = { id, en };

interface LanguageContextValue {
  lang: Language;
  setLang: (l: Language) => void;
  toggleLang: () => void;
  t: (key: string, vars?: Record<string, Primitive>) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

function getPath(dict: Dict, key: string): Primitive {
  const parts = key.split(".");
  let cur: Dict | Primitive = dict;
  for (const p of parts) {
    if (cur && typeof cur === "object" && p in (cur as Dict)) {
      cur = (cur as Dict)[p];
    } else {
      return key;
    }
  }
  return typeof cur === "string" || typeof cur === "number" ? cur : key;
}

function getInitialLang(): Language {
  if (typeof window === "undefined") return "en";
  const stored = localStorage.getItem("buddio_lang");
  if (stored === "en" || stored === "id") return stored;
  return "en";
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");

  useEffect(() => {
    setLangState(getInitialLang());
  }, []);

  const setLang = useCallback((l: Language) => {
    setLangState(l);
    localStorage.setItem("buddio_lang", l);
  }, []);

  const toggleLang = useCallback(() => {
    setLang(lang === "id" ? "en" : "id");
  }, [lang, setLang]);

  const t = useCallback(
    (key: string, vars?: Record<string, Primitive>) => {
      let value: Primitive = getPath(dictionaries[lang], key);
      if (typeof value === "string" && vars) {
        for (const [k, v] of Object.entries(vars)) {
          value = value.replaceAll(`{${k}}`, String(v));
        }
      }
      return typeof value === "string" ? value : key;
    },
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
